### ISSUE TITLE
[BUG] Fix the Pipeline

### ISSUE THREAD

**Issue by jatiinyadav** [jatiinyadav/web-crawler#14]
![image](https://github.com/jatiinyadav/web-crawler/assets/73248007/8dad6c1a-873f-49d8-88ff-80b85b055208)

Please fix this pipeline. View the error [here.](https://github.com/jatiinyadav/web-crawler/actions/runs/9601326951)

**Comment by aayushdhiman01** [comment]
@jatiinyadav can i work on this issue? i am a vsoc contributor.
