### ISSUE TITLE
[DOCS] Add all issue templates

### ISSUE THREAD

**Issue by jatiinyadav** [jatiinyadav/web-crawler#4]
1. Bug Report
2. Feature Request
3. Custom Template

**Comment by Mews** [comment]
What do you mean by custom template?

**Comment by jatiinyadav** [comment]
> What do you mean by custom template?

A template where contributor can create an issue according to them.

**Comment by Mews** [comment]
So a blank issue?

**Comment by jatiinyadav** [comment]
Yes
